// Generated by IB v0.8.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <CoreGraphics/CoreGraphics.h>
#import <Foundation/Foundation.h>
#import <SpriteKit/SpriteKit.h>
#import <UIKit/UIKit.h>
#import <SafariServices/SafariServices.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface PKCERootViewController: UIViewController

@property IBOutlet UIButton * login_button;

-(IBAction) start_dancing;

@end

