source 'https://rubygems.org'

gem 'rake'
# Add your dependencies here:

gem 'ib'
gem 'sugarcube', require: 'sugarcube-all'
gem 'bubble-wrap'
gem 'bubble-wrap-http'
gem 'motion-support'
gem 'rm-digest', git: 'git@github.com:tmeinlschmidt/rm-digest.git'